<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Frame</name>
   <tag></tag>
   <elementGuidId>742047c3-1960-49a4-9552-3b3898a93b48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'singleframe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>singleframe</value>
      <webElementGuid>ab188f73-f408-4030-b1e0-756e5a0f5a24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SingleFrame</value>
      <webElementGuid>f33f3f48-09fb-407f-8172-1e298052e63d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
