<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Address</name>
   <tag></tag>
   <elementGuidId>dbf1e32e-fa7a-43bb-98af-990213fbcefa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#address</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='address']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cbe8bac9-a6d3-49db-93af-5a1c3f063560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ab72c1c0-3818-48f7-99a9-6cb6f158a82b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address</value>
      <webElementGuid>be4bf818-9557-43b3-9843-2e2c0d0a5987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address</value>
      <webElementGuid>ee97fca3-a31e-40c6-9b5b-a95228854600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>123 Main St.</value>
      <webElementGuid>a6393858-591c-420b-b0a6-39a9e891397e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address&quot;)</value>
      <webElementGuid>b870ce78-1c5b-4609-ab8c-fa522f1826b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='address']</value>
      <webElementGuid>801a577b-95a6-4d99-9152-db6ce001c12b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>96ead678-2999-4beb-afd0-39af1eb05014</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'address' and @id = 'address' and @placeholder = '123 Main St.']</value>
      <webElementGuid>028bd774-e238-4b99-b7c5-cc74b869847d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
