<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CreditCardNumber</name>
   <tag></tag>
   <elementGuidId>69f8e6e4-2c2d-46bc-be54-7ee2a7a85007</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#creditCardNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='creditCardNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bbc45bf5-195f-4e12-b96c-c5c625ac9615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>192e74fc-7e44-46c7-b332-e1e2e327691f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>creditCardNumber</value>
      <webElementGuid>91c97952-0d17-4cc8-961e-b2f231ea1c95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>creditCardNumber</value>
      <webElementGuid>31089054-ea95-4a30-80b1-128b13f0a824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Credit Card Number</value>
      <webElementGuid>f52e96a0-0cde-47c9-b2e1-01e7ce918961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;creditCardNumber&quot;)</value>
      <webElementGuid>22d423f7-3452-4a3f-87e1-670409c714b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='creditCardNumber']</value>
      <webElementGuid>34563d34-7ae6-488d-b30d-a33c17b7fe4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/input</value>
      <webElementGuid>55045dc1-d1a8-4dc5-a831-0b9b5e5bc2b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'creditCardNumber' and @name = 'creditCardNumber' and @placeholder = 'Credit Card Number']</value>
      <webElementGuid>bf87c2dc-9122-42f3-be1d-a3a0ede41ad6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
