<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CreditCardMonth</name>
   <tag></tag>
   <elementGuidId>f26b19cd-b724-4790-bb89-5202ee58d2cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#creditCardMonth</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='creditCardMonth']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ec167fca-3ba9-448d-9239-ba23138ea908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8159dec7-37d7-4ae3-8a73-131b6f8d019c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>creditCardMonth</value>
      <webElementGuid>5380f19a-2dbf-4695-ae96-38cdf891c7ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>creditCardMonth</value>
      <webElementGuid>5c6c4b46-392a-40dc-906b-a718b2f44d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Month</value>
      <webElementGuid>f64b4257-9168-4ca0-b260-1af7ada90ced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>07357bde-7ed9-4034-b78c-cb2d9aae7f51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;creditCardMonth&quot;)</value>
      <webElementGuid>966b3d45-37be-482f-a4cf-d181da450c32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='creditCardMonth']</value>
      <webElementGuid>33fa3c86-91da-4db3-9dfc-59fbe36a6987</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/input</value>
      <webElementGuid>e1c537d6-9377-4a14-9a5c-b9ea2b4151af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'creditCardMonth' and @name = 'creditCardMonth' and @placeholder = 'Month']</value>
      <webElementGuid>87f3b214-191d-4c9a-a47b-4510ba997090</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
