<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CreditCardYear</name>
   <tag></tag>
   <elementGuidId>2ef0d1e3-40c2-43c5-987c-1256fe27ae6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#creditCardYear</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='creditCardYear']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4ed1a3da-98a4-40e4-b1b5-4f04c54f09dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2af4582d-e855-4a3a-b556-4ed44fca7286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>creditCardYear</value>
      <webElementGuid>85b5d55d-de06-49d2-93b7-3b2e453dd14c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>creditCardYear</value>
      <webElementGuid>f4f85bf0-4737-4ed0-aa2d-a0183de8c206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Year</value>
      <webElementGuid>6946aac1-0123-4649-85e4-e1dc69b59b2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2017</value>
      <webElementGuid>7663a8df-8269-4f43-9ba7-785a6cf7fa87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;creditCardYear&quot;)</value>
      <webElementGuid>b7962afe-ec49-4c5c-aef7-833b0256002d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='creditCardYear']</value>
      <webElementGuid>93c7e130-c96b-4b78-b637-1f35f62fa600</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/input</value>
      <webElementGuid>f47bd740-c2b9-4e8f-840c-70c68aed684f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'creditCardYear' and @name = 'creditCardYear' and @placeholder = 'Year']</value>
      <webElementGuid>502e56ad-ebfa-4670-9763-c3051a8186b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
