<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Name</name>
   <tag></tag>
   <elementGuidId>4c31cf16-1ec0-4d9d-84b8-0cf0c390d6dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>54b2105b-01aa-44c6-beb1-de5ec022ac46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputName</value>
      <webElementGuid>3ae4da8a-4a65-4d47-aec5-9fdd55aadf20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>First Last</value>
      <webElementGuid>93f50c9e-25e8-49a0-9732-5e0c3d76e5a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>inputName</value>
      <webElementGuid>1e8248f2-a861-4057-af3c-585e3601e030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cc2c8570-4913-4ad1-8f84-d422b799d091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputName&quot;)</value>
      <webElementGuid>2e020be1-6fd8-4505-b61d-5e7d67761574</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputName']</value>
      <webElementGuid>744871f6-431d-4ee6-983a-1fb7867b3a6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>111302ff-7e53-4ac2-a21f-eb62c36847da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inputName' and @placeholder = 'First Last' and @name = 'inputName' and @type = 'text']</value>
      <webElementGuid>4994ba35-51a3-44d3-a6ca-62433121c836</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
