<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NameOnCard</name>
   <tag></tag>
   <elementGuidId>84dee516-0a85-45ac-9ff5-cb7ac30a15ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nameOnCard</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nameOnCard']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>22a9cc56-539c-4063-b163-a776192b392f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d635ece9-6fed-4f24-a666-8a013c98dd01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nameOnCard</value>
      <webElementGuid>34ba53e5-765e-40e9-ba4e-b122c59bcdd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>John Smith</value>
      <webElementGuid>101ab56f-dab0-4852-901a-b9c01035912d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nameOnCard</value>
      <webElementGuid>8f4c12d8-1d0e-4f2b-a02a-860e0dc0e790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nameOnCard&quot;)</value>
      <webElementGuid>a519c690-2e8e-4d45-b343-68999dc00811</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nameOnCard']</value>
      <webElementGuid>ff93b2e6-56eb-415c-97e7-8d26c824bbbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/input</value>
      <webElementGuid>732c7b88-b12e-4908-bb86-3a24bc85700d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'nameOnCard' and @placeholder = 'John Smith' and @name = 'nameOnCard']</value>
      <webElementGuid>851b4d77-8a75-4a55-9dd8-631057ff87c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
