<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>State</name>
   <tag></tag>
   <elementGuidId>10c1230f-0e68-461d-8b8e-591fa97b8355</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#state</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='state']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>41a68ba7-1298-42ff-a81c-e98d58949adb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>633437b2-214e-4c56-92e6-2178a862cb6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>state</value>
      <webElementGuid>1a9f03c1-e5a6-46c4-b9a6-3c0fded3130e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>state</value>
      <webElementGuid>6180ed92-d4d6-43c2-bc88-75c8b61579c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>State</value>
      <webElementGuid>e765c597-173b-4ed8-8033-6ffe3c70aca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;state&quot;)</value>
      <webElementGuid>2a921d4f-bdfe-4d3c-919e-16c7ead86c98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='state']</value>
      <webElementGuid>980c6012-6e83-4357-bf5a-04a5575a53f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>a4f4acbb-53aa-4fe1-b54d-17b0b0ac43b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'state' and @id = 'state' and @placeholder = 'State']</value>
      <webElementGuid>813407cb-4f52-4650-8f20-f743cb2d6096</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
