<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Languages</name>
   <tag></tag>
   <elementGuidId>2a816748-5122-4cc4-bbd0-11d6c9aae912</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#msdd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='msdd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7a73fe32-8bdb-467f-b689-348ebae28669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-autocomplete-multiselect ui-state-default ui-widget</value>
      <webElementGuid>8ae4afca-b4e3-488a-a882-fb1ba0de80da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>msdd</value>
      <webElementGuid>92ee2bea-7d3e-4296-a338-6522b8a797ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;msdd&quot;)</value>
      <webElementGuid>ce666488-b98d-419c-9878-8741259b6f71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='msdd']</value>
      <webElementGuid>4d687878-464e-4f92-a00c-ba4703489367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basicBootstrapForm']/div[7]/div/multi-select/div</value>
      <webElementGuid>c235bb51-b156-4fad-83b0-3b64a409ab14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Languages'])[1]/following::div[2]</value>
      <webElementGuid>0fb459cd-1eee-4c6c-b78c-139ca9785ca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hockey'])[1]/following::div[3]</value>
      <webElementGuid>e87f5ec7-51f7-4a4d-a8d0-2c2fb9d11bea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Arabic'])[1]/preceding::div[1]</value>
      <webElementGuid>218d63eb-53e0-4ce4-86a7-61eb69c5e718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bulgarian'])[1]/preceding::div[1]</value>
      <webElementGuid>ec4f2d90-7542-479f-8930-5ceafb4da368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//multi-select/div</value>
      <webElementGuid>198e9836-fdfe-4688-9e93-201fbfc485bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'msdd']</value>
      <webElementGuid>afa6e190-955d-4c0e-92e8-6b02ca956ce6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
