<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Month</name>
   <tag></tag>
   <elementGuidId>40c927a9-a3fc-4196-9439-f066be5361f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//select[@type='text'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f6eb9c61-477f-4912-908f-289868f351bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3c84eec6-bef8-460c-a725-3de0ab655101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-invalid ng-invalid-required ng-touched</value>
      <webElementGuid>b507ec75-8b70-4d59-9736-c82c3389b08c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Month</value>
      <webElementGuid>958baa20-ba0d-49af-ab56-10c369eb18fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>monthbox</value>
      <webElementGuid>f798f6aa-5226-4971-8ac2-988a05370995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-init</name>
      <type>Main</type>
      <value>monthbox=''</value>
      <webElementGuid>8bd17594-6b44-41bf-8cab-defaeb74ab00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Month
                                January
                                February
                                March
                                April
                                May
                                June
                                July
                                August
                                September
                                October
                                November
                                December
                            </value>
      <webElementGuid>267f57a7-8523-413b-90c3-adcba15adc7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basicBootstrapForm&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-md-3 col-xs-3 col-sm-3&quot;]/select[@class=&quot;form-control ng-pristine ng-invalid ng-invalid-required ng-touched&quot;]</value>
      <webElementGuid>5382350f-80d0-4257-9a51-0357f931c30a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//select[@type='text'])[4]</value>
      <webElementGuid>97b04ba1-7748-45e8-98ff-7e01b360b0db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basicBootstrapForm']/div[11]/div[2]/select</value>
      <webElementGuid>d6903db0-d8aa-4b86-92d5-7e53ccf9a48e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date Of Birth'])[1]/following::select[2]</value>
      <webElementGuid>2c1b32c0-d3f4-4240-b758-798ae01264c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Country :'])[1]/following::select[3]</value>
      <webElementGuid>ed8e5447-483f-4370-b6c3-71a747125915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/preceding::select[2]</value>
      <webElementGuid>3b62ea06-fdfc-48b3-9073-dda0ff00dedb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm Password'])[1]/preceding::select[2]</value>
      <webElementGuid>68d252a5-a312-4bf7-9ec0-9d6212cfb42b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>191b29f5-d9fa-4945-9e15-c4a0e87461e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@type = 'text' and @placeholder = 'Month' and (text() = '
                                Month
                                January
                                February
                                March
                                April
                                May
                                June
                                July
                                August
                                September
                                October
                                November
                                December
                            ' or . = '
                                Month
                                January
                                February
                                March
                                April
                                May
                                June
                                July
                                August
                                September
                                October
                                November
                                December
                            ')]</value>
      <webElementGuid>eee5edba-e347-4a02-b933-6e9cc65a6a4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
